export enum WeatherParameter {
  AirPressureAtMeanSeaLevel = "air_pressure_at_mean_sea_level",
  AirTemperature = "air_temperature",
  CloudAreaFraction = "cloud_area_fraction",
  CloudBaseAltitude = "cloud_base_altitude",
  CloudTopAltitude = "cloud_top_altitude",
  HighTypeCloudAreaFraction = "high_type_cloud_area_fraction",
  LowTypeCloudAreaFraction = "low_type_cloud_area_fraction",
  MediumTypeCloudAreaFraction = "medium_type_cloud_area_fraction",
  PrecipitationAmountMax = "precipitation_amount_max",
  PrecipitationAmountMean = "precipitation_amount_mean",
  PrecipitationAmountMeanDeterministic = "precipitation_amount_mean_deterministic",
  PrecipitationAmountMedian = "precipitation_amount_median",
  PrecipitationAmountMin = "precipitation_amount_min",
  PrecipitationFrozenPart = "precipitation_frozen_part",
  PredominantPrecipitationTypeAtSurface = "predominant_precipitation_type_at_surface",
  ProbabilityOfFrozenPrecipitation = "probability_of_frozen_precipitation",
  ProbabilityOfPrecipitation = "probability_of_precipitation",
  RelativeHumidity = "relative_humidity",
  SymbolCode = "symbol_code",
  ThunderstormProbability = "thunderstorm_probability",
  VisibilityInAir = "visibility_in_air",
  WindFromDirection = "wind_from_direction",
  WindSpeed = "wind_speed",
  WindSpeedOfGust = "wind_speed_of_gust",
}
